tap "homebrew/cask"
tap "d12frosted/emacs-plus"
cask "docker"
brew "kubectl"
brew "minikube"
brew "zsh"
brew "rg"
brew "fzf"
cask "macvim"
cask "rowanj-gitx"
cask "iterm2"
brew "emacs-plus", args: ["with-no-titlebar"]
brew "git"
brew "vim"
